mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
  :tag => '4.11.0'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :tag => '2.2.1'

mod 'mesos',
  :git => 'https://github.com/deric/puppet-mesos.git',
  :tag => 'v0.6.4'

mod 'datacat',
  :git => 'https://github.com/richardc/puppet-datacat.git',
  :tag => '0.6.2'

mod 'zookeeper',
  :git => 'https://github.com/deric/puppet-zookeeper.git',
  :tag => 'v0.4.2'
